function buildRoadmapPrompt({
  role,
  skillLevel,
  goal,
  timeAvailable,
  companyName,
  readinessScore,
  performanceRating,
  quizScore,
  strengths,
  skillGaps,
  requiredSkills,
}) {
  const extraContext = [
    companyName ? `- companyName: ${companyName}` : null,
    readinessScore != null ? `- readinessScore: ${readinessScore}/100` : null,
    performanceRating != null ? `- performanceRating: ${performanceRating}/10` : null,
    quizScore != null ? `- quizScore: ${quizScore}/100` : null,
    Array.isArray(strengths) && strengths.length ? `- strengths: ${strengths.join(', ')}` : null,
    Array.isArray(skillGaps) && skillGaps.length ? `- skillGaps: ${skillGaps.join(', ')}` : null,
    Array.isArray(requiredSkills) && requiredSkills.length ? `- requiredSkills: ${requiredSkills.join(', ')}` : null,
  ].filter(Boolean);

  return [
    'You are an expert career mentor and learning architect.',
    'Create a practical, personalized roadmap for the user input below.',
    'Prioritize skill-gap closure while leveraging strengths and readiness data.',
    '',
    'User Input:',
    `- role: ${role}`,
    `- skillLevel: ${skillLevel}`,
    `- goal: ${goal}`,
    `- timeAvailable: ${timeAvailable}`,
    ...extraContext,
    '',
    'Rules:',
    '- Return ONLY valid JSON (no markdown, no backticks, no explanation).',
    '- The roadmap must be realistic, specific, and phase-based.',
    '- Include 3 to 6 phases.',
    '- Each phase must include topic progression from fundamentals to advanced practice.',
    '- Include one mini project per phase.',
    '- Include high-quality resources and practical platforms.',
    '- Include 2 to 4 relevant videoLinks per phase with title and url.',
    '- Use concise, clear language suitable for students and early-career professionals.',
    '',
    'Return this exact JSON shape:',
    '{',
    '  "roadmapTitle": "",',
    '  "description": "",',
    '  "phases": [',
    '    {',
    '      "phase": "",',
    '      "duration": "",',
    '      "topics": [""],',
    '      "project": "",',
    '      "resources": [""],',
    '      "videoLinks": [',
    '        { "title": "", "url": "" }',
    '      ],',
    '      "platforms": ["" ]',
    '    }',
    '  ]',
    '}',
  ].join('\n');
}

module.exports = { buildRoadmapPrompt };
